spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:robella}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:123654789}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
