spring:
  config:
    activate:
      on-profile: sqlite
  datasource:
    url: jdbc:sqlite:${SQLITE_DB_PATH:./data/robella.db}
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 30000
      connection-timeout: 30000
      auto-commit: true
      connection-test-query: SELECT 1
  
  # SQLite 的 Flyway 配置
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:db/migration/sqlite
    baseline-on-migrate: true
    validate-on-migrate: true
